name: Python CI

##Trigger the workflow on any push to the main branch or pull request
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs_on: ubuntu-latest 

        steps:
            # STEP 1: Check out the code from the Repository
            - name: Check out code
              uses: actions/checkout@v2

            # STEP 2: Set up python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                 python-version: '3.8'
            
            # STEP 3: 
            - name: Install Dependencies 
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # Step 4:
            - name: Run Tests
              run: pytest
            






        

        

